// @vitest-environment node
/**
 * End-to-end web-port parity: JS WAV read -> JS mel frontend -> the real
 * fp16 ONNX encoder+CTC graph -> JS Sanskrit-slice decode, compared against
 * the decode strings the Python pipeline produced for the same audio
 * (fixtures generated by export_web_assets.py).
 *
 * Runs only when the local model assets exist (models-local/chant is
 * git-ignored: the Su-śrotā weights carry no explicit licence grant and are
 * provisioned per machine — research/pronunciation-ai/06). In CI without
 * assets the suite skips rather than fails.
 *
 * onnxruntime-node and onnxruntime-web's wasm backend share the same ONNX
 * Runtime core and CPU kernels; this suite verifies numerics of the ported
 * pipeline. Browser-specific behaviour (asset loading, WebGPU/wasm providers,
 * latency) is exercised in the app itself.
 */
import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'
import verifyParity from '../fixtures/chant/verify-parity.json'
import { readWav16kMono } from '../helpers/readWav'
import { computeLogMelFeatures } from '../../services/chantAnalysis/melFrontend'
import {
  decodeVariants,
  type SanskritTokenizer,
} from '../../services/chantAnalysis/ctcDecode'

const ASSET_DIR = path.resolve(process.cwd(), 'models-local', 'chant')
const CLIP_DIR = path.resolve(
  process.cwd(),
  'research',
  'pronunciation-ai',
  'scripts',
  'clips',
)
const MODEL_PATH = path.join(ASSET_DIR, 'susrota_ctc_fp16.onnx')

const assetsPresent =
  existsSync(MODEL_PATH) &&
  existsSync(path.join(ASSET_DIR, 'frontend.json')) &&
  existsSync(path.join(ASSET_DIR, 'sa_tokenizer.json')) &&
  existsSync(CLIP_DIR)

interface FixtureEntry {
  clipId: string
  kind: string
  expectedText: string
  decodes: string[]
}

const entries = (verifyParity as { entries: FixtureEntry[] }).entries

function b64ToF32(b64: string): Float32Array {
  const bytes = Buffer.from(b64, 'base64')
  const copy = new Uint8Array(bytes.byteLength)
  copy.set(bytes)
  return new Float32Array(copy.buffer)
}

function clipPath(clipId: string): string {
  if (clipId.startsWith('_hardneg')) return path.join(CLIP_DIR, clipId)
  return path.join(CLIP_DIR, 'held_out', `${clipId}.wav`)
}

describe.skipIf(!assetsPresent)('chant model parity (local assets)', () => {
  it(
    'reproduces the Python decode variants for every fixture clip',
    { timeout: 300_000 },
    async () => {
      const ort = await import('onnxruntime-node')
      const frontend = JSON.parse(
        readFileSync(path.join(ASSET_DIR, 'frontend.json'), 'utf-8'),
      ) as {
        nFft: number
        winLength: number
        hopLength: number
        nMels: number
        preemph: number
        logZeroGuard: number
        normalizeStdEps: number
        magPower: number
        padTo: number
        windowB64: string
        melFilterbankB64: string
        vocabSize: number
      }
      const tokenizer = JSON.parse(
        readFileSync(path.join(ASSET_DIR, 'sa_tokenizer.json'), 'utf-8'),
      ) as SanskritTokenizer & { pieces: string[] }
      const constants = {
        window: b64ToF32(frontend.windowB64),
        filterbank: b64ToF32(frontend.melFilterbankB64),
      }

      const session = await ort.InferenceSession.create(MODEL_PATH, {
        intraOpNumThreads: 4,
        executionProviders: ['cpu'],
      })

      // Each unique clip is decoded once; fixture entries reuse audio.
      const uniqueClipIds = [...new Set(entries.map((e) => e.clipId))]
      const decodesByClip = new Map<string, string[]>()
      let inferenceSeconds = 0
      let audioSeconds = 0

      for (const clipId of uniqueClipIds) {
        const audio = readWav16kMono(clipPath(clipId))
        audioSeconds += audio.length / 16000
        const feats = computeLogMelFeatures(audio, frontend, constants)
        const t0 = performance.now()
        const output = await session.run({
          audio_signal: new ort.Tensor('float32', feats.data, [
            1,
            frontend.nMels,
            feats.frames,
          ]),
          length: new ort.Tensor(
            'int64',
            BigInt64Array.from([BigInt(feats.featLen)]),
            [1],
          ),
        })
        inferenceSeconds += (performance.now() - t0) / 1000
        const logProbs = output.logprobs
        const [batch, outFrames, vocab] = logProbs.dims
        expect(batch).toBe(1)
        expect(vocab).toBe(frontend.vocabSize)
        const variants = decodeVariants(
          logProbs.data as Float32Array,
          outFrames,
          vocab,
          tokenizer,
        )
        decodesByClip.set(
          clipId,
          variants.map((v) => v.text),
        )
      }

      let comparedVariants = 0
      const mismatches: string[] = []
      for (const entry of entries) {
        const produced = decodesByClip.get(entry.clipId)
        expect(produced).toBeDefined()
        if (entry.kind === 'silence') {
          // Digital silence puts every logit at the numerical noise floor,
          // where the decode is version-dependent garbage (measured: ORT
          // 1.30.0/Python vs 1.20.1/Node produce different garbage strings
          // for this clip and identical strings for all real audio). String
          // parity is meaningless there; the property that matters is that
          // garbage never scores as a match against the expected text.
          const { scoreAgainstText } = await import(
            '../../services/chantAnalysis/scoreAgainstText'
          )
          const results = scoreAgainstText(entry.expectedText, produced!)
          expect(results.filter((r) => r.label === 'correct')).toEqual([])
          continue
        }
        for (let v = 0; v < entry.decodes.length; v++) {
          comparedVariants += 1
          if (produced![v] !== entry.decodes[v]) {
            mismatches.push(
              `${entry.kind}:${entry.clipId} variant ${v}\n  py: ${entry.decodes[v]}\n  ts: ${produced![v]}`,
            )
          }
        }
      }

      // Every non-degenerate entry, all four variants, string-identical.
      expect(comparedVariants).toBeGreaterThanOrEqual((entries.length - 1) * 4)
      expect(mismatches, mismatches.join('\n')).toEqual([])

      const rtf = inferenceSeconds / audioSeconds

      console.log(
        `[chant model parity] ${uniqueClipIds.length} clips, ` +
          `${comparedVariants} decode variants compared, 0 mismatches. ` +
          `onnxruntime-node CPU RTF=${rtf.toFixed(3)} ` +
          `(${inferenceSeconds.toFixed(1)}s inference / ${audioSeconds.toFixed(1)}s audio)`,
      )
    },
  )
})

describe.skipIf(assetsPresent)('chant model parity (assets absent)', () => {
  it('skips cleanly when local model assets are not provisioned', () => {
    expect(assetsPresent).toBe(false)
  })
})
