/**
 * Devanagari text helpers for the on-device chant analyzer.
 *
 * This is a line-for-line TypeScript port of
 * `research/pronunciation-ai/scripts/common_text.py`, and MUST stay
 * behaviourally identical to it: the committed fixtures in
 * `src/test/fixtures/chant/` were generated by the Python original, and
 * `chantText.test.ts` holds this port to byte-identical outputs.
 *
 * Every character class below is written with \u escapes on purpose: editors
 * and diff tools silently re-normalise Devanagari literals (NFC decomposes
 * the precomposed nukta consonants U+0958–U+095F), which would corrupt a
 * literal range. Do not replace the escapes with literals.
 *
 * Same known limitation as the original: `segmentAksharas` is a fast
 * orthographic segmenter, not a full Sanskrit syllabifier.
 */

const VIRAMA = '्'
const ANUSVARA = 'ं'

// DANDA (U+0964), DOUBLE DANDA (U+0965), AVAGRAHA (U+093D), OM (U+0950),
// ASCII pipe, Vedic accents (U+0951–U+0954, U+1CD0–U+1CFA), Devanagari
// digits (U+0966–U+096F) and ASCII digits. The accent ranges are lone
// combining marks; byte-level correctness is pinned by the parity fixtures.
const DROP_CHARS =
  // eslint-disable-next-line no-misleading-character-class -- stripping lone combining Vedic accents is exactly the intent (parity with common_text.py)
  /[।॥ऽॐ|॑-॔᳐-ᳺ०-९0-9]/g

const WHITESPACE = /\s+/g

/** Content-only normalisation for scoring. Keeps letters + combining marks. */
export function normaliseDevanagari(text: string): string {
  return text
    .normalize('NFC')
    .replace(DROP_CHARS, ' ')
    .replace(WHITESPACE, ' ')
    .trim()
}

export function stripSpaces(text: string): string {
  return text.normalize('NFC').replace(DROP_CHARS, '').replace(WHITESPACE, '')
}

// --- Devanagari akshara (orthographic syllable) segmentation ---------------
// Ranges mirror common_text.py exactly: vowels U+0904–U+0914, U+0960, U+0961,
// U+0972–U+0977 · consonants U+0915–U+0939, U+0958–U+095F, U+0978–U+097F ·
// matras U+093A–U+093C, U+093E–U+094C, U+094E, U+094F, U+0955–U+0957,
// U+0962, U+0963 · trailing marks U+0900–U+0903 · nukta U+093C.

const VOWEL_BODY = 'ऄ-औॠॡॲ-ॷ'
const CONS_BODY = 'क-हक़-य़ॸ-ॿ'
const MATRA_BODY = 'ऺ-़ा-ौॎॏॕ-ॗॢॣ'
const TRAIL_BODY = 'ऀ-ः'

const INDEP_VOWEL = `[${VOWEL_BODY}]`
const CONSONANT = `[${CONS_BODY}]`
const MATRA = `[${MATRA_BODY}]`
const TRAIL = `[${TRAIL_BODY}]`

// The final "(?:CONS virama (?![CONS VOWEL]))?" clause attaches a phrase-final
// halanta consonant to the akshara it closes; the negative lookahead keeps a
// conjunct onset opening the NEXT akshara as normal.
const AKSHARA_RE = new RegExp(
  '(?:' +
    `${INDEP_VOWEL}${TRAIL}?` +
    '|' +
    `(?:${CONSONANT}${VIRAMA})*${CONSONANT}़?${MATRA}*${TRAIL}*` +
    `(?:${CONSONANT}${VIRAMA}(?![${CONS_BODY}${VOWEL_BODY}]))?` +
    ')',
  'gu',
)

/** Split normalised Devanagari into a list of akshara strings (no spaces). */
export function segmentAksharas(text: string): string[] {
  const stripped = stripSpaces(text)
  const matches = stripped.match(AKSHARA_RE)
  return matches ? matches.filter((m) => m.length > 0) : []
}

export interface AksharaSpan {
  akshara: string
  /** Char offsets into the input string (which must already be space-free). */
  start: number
  end: number
}

/**
 * Like `segmentAksharas`, but over an already-canonicalised (space-free)
 * string and with char spans, for mapping aksharas back to decode timing.
 * The concatenated aksharas may skip stray non-akshara characters; spans are
 * therefore not necessarily contiguous.
 */
export function segmentAksharasWithSpans(canonical: string): AksharaSpan[] {
  const spans: AksharaSpan[] = []
  for (const match of canonical.matchAll(AKSHARA_RE)) {
    if (match[0].length === 0) continue
    spans.push({
      akshara: match[0],
      start: match.index,
      end: match.index + match[0].length,
    })
  }
  return spans
}

/** Single-char membership test for the drop set (danda, om, digits, ...). */
export function isDroppedChar(ch: string): boolean {
  DROP_CHARS.lastIndex = 0
  return DROP_CHARS.test(ch)
}

// --- canonicalisation used before alignment --------------------------------

const DOUBLED_MARK = /([ंः़])\1+/g
const MA_VIRAMA_FINAL = /म्(?=\s|$)/g

export function canonicaliseForAlignment(text: string): string {
  let out = text.normalize('NFC')
  out = out.replace(MA_VIRAMA_FINAL, ANUSVARA)
  out = out.replace(DOUBLED_MARK, '$1')
  return stripSpaces(out)
}

// --- edit distance / alignment (Needleman-Wunsch, unit costs) ---------------

export type AlignmentPair = [string | null, string | null]

/**
 * Return (ref token | null, hyp token | null) alignment pairs. The backtrace
 * order (diagonal, then deletion, then insertion) matches the Python original
 * exactly — alignment ties resolve identically or the parity fixtures fail.
 */
export function align(ref: string[], hyp: string[]): AlignmentPair[] {
  const n = ref.length
  const m = hyp.length
  const dp: number[][] = Array.from({ length: n + 1 }, () =>
    new Array<number>(m + 1).fill(0),
  )
  for (let i = 1; i <= n; i++) dp[i][0] = i
  for (let j = 1; j <= m; j++) dp[0][j] = j
  for (let i = 1; i <= n; i++) {
    for (let j = 1; j <= m; j++) {
      const cost = ref[i - 1] === hyp[j - 1] ? 0 : 1
      dp[i][j] = Math.min(
        dp[i - 1][j - 1] + cost,
        dp[i - 1][j] + 1,
        dp[i][j - 1] + 1,
      )
    }
  }
  let i = n
  let j = m
  const out: AlignmentPair[] = []
  while (i > 0 || j > 0) {
    if (
      i > 0 &&
      j > 0 &&
      dp[i][j] === dp[i - 1][j - 1] + (ref[i - 1] === hyp[j - 1] ? 0 : 1)
    ) {
      out.push([ref[i - 1], hyp[j - 1]])
      i -= 1
      j -= 1
    } else if (i > 0 && dp[i][j] === dp[i - 1][j] + 1) {
      out.push([ref[i - 1], null])
      i -= 1
    } else {
      out.push([null, hyp[j - 1]])
      j -= 1
    }
  }
  out.reverse()
  return out
}

/** Levenshtein over characters of space-stripped strings / len(ref). */
export function charErrorRate(ref: string, hyp: string): number {
  const r = stripSpaces(ref)
  const h = stripSpaces(hyp)
  if (r.length === 0) return h.length === 0 ? 0 : 1
  let prev = Array.from({ length: h.length + 1 }, (_v, k) => k)
  for (let ri = 1; ri <= r.length; ri++) {
    const cur = new Array<number>(h.length + 1)
    cur[0] = ri
    for (let hi = 1; hi <= h.length; hi++) {
      cur[hi] = Math.min(
        prev[hi] + 1,
        cur[hi - 1] + 1,
        prev[hi - 1] + (r[ri - 1] === h[hi - 1] ? 0 : 1),
      )
    }
    prev = cur
  }
  return prev[h.length] / r.length
}
